title: Unused
tagline: A command line tool to identify unused code.
description: >
  Unused is a command line tool to identify unused code.
baseurl: ""
url: "https://unused.codes"
links:
  social:
    github: https://github.com/joshuaclayton/unused
    twitter: https://twitter.com/joshuaclayton
  travis_url: https://travis-ci.org/joshuaclayton/unused
  travis_svg: //travis-ci.org/joshuaclayton/unused.svg?branch=master
  alt_install_options: https://github.com/joshuaclayton/unused#installing-and-updating
  hackage: http://hackage.haskell.org/package/unused
  gif:
    image: //i.giphy.com/3o7qDT1I4OfQxnJTvW.gif
    url: https://i.giphy.com/3o7qDT1I4OfQxnJTvW.gif
  homebrew_formulae: https://github.com/joshuaclayton/homebrew-formulae
  homebrew: http://brew.sh/
  ctags: http://ctags.sourceforge.net/
  ag: http://geoff.greer.fm/ag/
  languages:
    ruby: https://www.ruby-lang.org/
    elixir: http://elixir-lang.org/

pull_requests:
- url: https://github.com/exercism/exercism.io/pull/2947
  lines_added: 0
  lines_removed: 1501
  project: Exercism.io
- url: https://github.com/houndci/hound/pull/1169
  lines_added: 0
  lines_removed: 118
  project: HoundCI
- url: https://github.com/rubygems/rubygems.org/pull/1319
  lines_added: 1
  lines_removed: 39
  project: Rubygems.org

markdown: kramdown
